/**
 * Stand-in for `virtual:pwa-register/react`.
 *
 * That module is generated by vite-plugin-pwa, which vitest.config.ts leaves
 * out on purpose — it builds a service worker, which no test wants. Without
 * this, anything that renders <App/> fails to resolve the update banner's
 * import, so the app as a whole could not be tested at all.
 */
export function useRegisterSW() {
  return {
    needRefresh: [false, () => undefined] as [boolean, (v: boolean) => void],
    updateServiceWorker: () => Promise.resolve(),
  };
}
